baseURL = "https://blog.zhaojq.top"
languageCode = "zh-cn"
title = "古道长亭"
theme = "m10c"
paginate = 10
[menu]
  [[menu.main]]
    name                   = "首页"
    weight                 = 1
    identifier             = "首页"
    url                    = "/posts/"
    title                  = "首页"
  [[menu.main]]
    name                   = "技术"
    weight                 = 2
    identifier             = "技术"
    url                    = "/tecs/"
    title                  = "技术分享"
  [[menu.main]]
    name                   = "系列"
    weight                 = 3
    identifier             = "系列"
    url                    = "/books/"
    title                  = "技术系列"
  [[menu.main]]
    name                   = "随笔"
    weight                 = 4
    identifier             = "随笔"
    url                    = "/free/"
    title                  = "生活随笔"
  [[menu.main]]
    name                   = "关于"
    weight                 = 5
    identifier             = "关于"
    url                    = "/about/"
    title                  = "关于"
[params]
  author = "zhaoxr"
  description = "The road through the summit is always difficult and lonely"
  avatar = "avatar.png"
  shortcutIcon = "shortcut.jpeg"
  bookmark = "bookmark.jpeg"

  [[params.social]]
    name = "github"
    url = "https://github.com/ixinglan"
  [[params.social]]
    name = "csdn"
    url = "https://me.csdn.net/qq_34581279"
  [[params.social]]
      name = "gitee"
      url = "https://gitee.com/ixinglan"

  # Brown theme
#  [params.style]
#    darkestColor = "#463625"
#    darkColor = "#2a3738"
#    primaryColor = "#eeee6a"
#    lightColor = "#96a879"
#    lightestColor = "#ffffff"

  # Green theme
#  [params.style]
#    darkestColor = "#315659"
#    darkColor = "#253031"
#    primaryColor = "#dad865"
#    lightColor = "#96a879"
#    lightestColor = "#fff"

  # Red and black theme
#  [params.style]
#    darkestColor = "#d35050"
#    darkColor = "#212121"
#    primaryColor = "#ffffff"
#    lightColor = "#a2a2a2"
#    lightestColor = "#d3d3d3"

  # self
  [params.style]
    darkestColor = "#242930"
    darkColor = "#212121"
    primaryColor = "#57cc8a"
    lightColor = "#fff"
    lightestColor = "#ffffff"
